apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secureops-api-policy
  namespace: secureops
spec:
  podSelector:
    matchLabels:
      app: secureops-api
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - protocol: TCP
          port: 8200
  egress:
    - ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 443
